server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  profiles:
    active: dev
  # database config
  datasource:
    url: jdbc:mysql://localhost:3350/marine_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      continue-on-error: true

  # Redis config
  data:
    redis:
      host: 127.0.0.1
      port: 16379
      #password: 123456
      database: 0
      timeout: 10000ms
      # Lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # Spring AI
  ai:
    dashscope:
      api-key: REDACTED_DASHSCOPE_KEY #REDACTED_APP_AI_KEY
      chat:
        options:
          model: deepseek-v3.2 #qwen-plus
        embedding:
          options:
            model: text-embedding-v3
    vectorstore:
      redis:
        initialize-schema: true
        index-name: custom-index
        prefix: custom-prefix
    openai:
      api-key: REDACTED_DASHSCOPE_KEY # API Key
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: glm-4-flash
          temperature: 0.7

  # static resources upload config
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/, file:./uploads/


jwt:
  secret: REDACTED_JWT_SECRET
  expiration: 86400000

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.gdou.marine.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  # LangChain4j AI config
  ai:
    api-key: REDACTED_APP_AI_KEY
    chat:
      model: qwen-plus-2025-12-01
    embedding:
      model: text-embedding-v3
      dimension: 1536
    vectorstore:
      redis:
        index-name: rag-index
        prefix: rag:chunk
  upload:
    base-dir: uploads
    avatar-dir: uploads/avatars
